name: Build Vite Project 

"on":
  push:
    branches: 
      - main
  pull_request: {} 
      
jobs: 
  build: 
    runs-on: ubuntu_latest
    
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/checkout@v4
        with: 
          node-version: '20'

      - name: Install dependencies 
        run: |
          if [-f package-lock.json]; then
            npm ic
          else 
            npm install
          fi

      - name: Build project 
        run: npm run build 

      - name: upload dist folder 
        uses: actions/uploud-artifact@v3
        with: 
              name: dist 
              path: dist

